recipe: default.v1
assistant_id: funny-founder
language: en
additional_languages:
  - "es"
pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: gemini_llm
policies:
  - name: FlowPolicy
  #- name: EnterpriseSearchPolicy
  #  vectore_store:
  #     type:
